### ISSUE TITLE
RNA secondary structure predict

### ISSUE THREAD

**Issue by cyxiang1027** [CatIIIIIIII/RNAErnie#10]
I want to use RNAErnie to predict the secondary structure of an RNA molecule in fasta format. How should I proceed?

**Comment by CatIIIIIIII** [comment]
You can try this one

```
"""
This file predicts sars-cov-2 secondary structure.

Author: wangning(wangning.roci@gmail.com)
Date  : 2023/6/10 15:08 PM
"""
import argparse

import paddle
from paddlenlp.utils.log import logger

import os.path as osp
from Bio import SeqIO
import numpy as np

import param_turner2004
from paddlenlp.transformers import ErnieModel

from arg_utils import print_config, set_seed
from rna_ernie import BatchConverter
from secondary_structure import MixedFold, SspTrainer

if __name__ == "__main__":
    # ========== Configuration
    logger.debug("Loading configuration.")
    parser = argparse.ArgumentParser(
        description='SARS CoV 2 secondary structure prediction.', add_help=True)
    # input
    parser.add_argument('--device',
                        type=str,
                        default='gpu',
                        choices=['gpu', 'cpu'],
                        help='Device for training, default to gpu.')
    parser.add_argument('--seed', type=int, default=0, help='Random seed.')

    parser.add_argument('--k_mer', type=int, default=1, help='Number of continuous nucleic acids to form a token.')
    parser.add_argument('--vocab_path', type=str, default="./data/vocab/", help='Local path for vocab file.')

    parser.add_argument('--data', type=str, default="data/sars_cov_2/sars_cov_2.fasta",
                        help='Local path for dataset or seqs seperated by comma.')
    parser.add_argument('--st_pos', type=int, default=0, help='Start position of the sequence.')
    parser.add_argument('--max_seq_len', type=int, default=302,
                        help='The maximum length for model input, including special tokens.')
    parser.add_argument('--batch_size', type=int, default=1, help='batch size')

    parser.add_argument('--model_name_or_path',
                        type=str,
                        default="./output3/BERT,ERNIE,MOTIF,PROMPT/checkpoint-129000",
                        help='The build-in pretrained LM or the path to local model parameters.')
    parser.add_argument('--model_path',
                        type=str,
                        default="./output_ft/ssp/RNAStrAlign/BERT,ERNIE,MOTIF,PROMPT",
                        help='The build-in pretrained LM or the path to local model parameters.')
    parser.add_argument('--no-split-lr', default=False, action='store_true')
    args = parser.parse_args()

    # post process
    if ".txt" not in args.vocab_path:
        args.vocab_path = osp.join(args.vocab_path,
                                   "vocab_" + str(args.k_mer) + "MER.txt")  # expected: "./data/vocab/vocab_6MER.txt"
    if args.model_path.split(".") != "pdparams":
        args.model_path = osp.join(args.model_path, "model_state.pdparams")
    print_config(args, "RNA Secondary Structure Prediction.")

    # ========== Set random seeds
    logger.debug("Set random seeds.")
    set_seed(args.seed)

    # ========== Set device
    logger.debug("Set device.")
    paddle.set_device(args.device)

    # ========== Prepare Data
    # load .fasta file by BioPython
    if ".fasta" in args.data:
        fasta = list(SeqIO.parse(args.data, "fasta"))
        data = [(x.id, str(x.seq)) for x in fasta]
        gt = None
    elif ".bpseq" in args.data:
        with open(args.data) as f:
            p = [0]
            s = ['']
            for line in f:
                line = line.rstrip('\n').split()
                idx, c, pair = line
                idx, pair = int(idx), int(pair)
                s.append(c)
                p.append(pair)
        data = [("RNA", ''.join(s))]
        gt = [(args.data.split("/")[-1], np.array(p))]
    else:
        data = [("RNA" + str(i), x) for i, x in enumerate(args.data.split(","))]

    # ========== Model
    # rna ernie model
    rna_em = ErnieModel.from_pretrained(args.model_name_or_path)
    # ssp model
    config = {
        'max_helix_length': 30,
        'embed_size': 64,
        'num_filters': (64, 64, 64, 64, 64, 64, 64, 64),
        'filter_size': (5, 3, 5, 3, 5, 3, 5, 3),
        'pool_size': (1, ),
        'dilation': 0,
        'num_lstm_layers': 2,
        'num_lstm_units': 32,
        'num_transformer_layers': 0,
        'num_hidden_units': (32, ),
        'num_paired_filters': (64, 64, 64, 64, 64, 64, 64, 64),
        'paired_filter_size': (5, 3, 5, 3, 5, 3, 5, 3),
        'dropout_rate': 0.5,
        'fc_dropout_rate': 0.5,
        'num_att': 8,
        'pair_join': 'cat',
        'no_split_lr': args.no_split_lr,
        'n_out_paired_layers': 3,
        'n_out_unpaired_layers': 0,
        'exclude_diag': True
    }
    ssp = MixedFold(init_param=param_turner2004, **config)
    ssp.set_state_dict(paddle.load(args.model_path))

    # ========== Batch Converter
    logger.debug("Loading converter.")
    batch_converter = BatchConverter(
        k_mer=args.k_mer,
        vocab_path=args.vocab_path,
        batch_size=args.batch_size,
        max_seq_len=args.max_seq_len,
        is_pad=False,
        st_pos=args.st_pos,
    )

    # ========== Training
    ssp_trainer = SspTrainer(args=args,
                             tokenizer=None,
                             model=ssp,
                             pretrained_model=rna_em)
    ssp_trainer.predict(batch_converter=batch_converter, data=data)
```

**Comment by cyxiang1027** [comment]
Thank you very much for your reply.

**Comment by cyxiang1027** [comment]
When I run the above script, the following error occurs:

Traceback (most recent call last):
  File "/usr/local/RNAErnie/sec.py", line 135, in <module>
    ssp_trainer = SspTrainer(args=args,
  File "/usr/local/RNAErnie/secondary_structure.py", line 1158, in __init__
    super(SspTrainer, self).__init__(
  File "/usr/local/RNAErnie/base_classes.py", line 167, in __init__
    self.name_pbar = self.compute_metrics.metrics[0]
AttributeError: 'NoneType' object has no attribute 'metrics'

**Comment by cyxiang1027** [comment]
When I run the above script, the following error occurs:

Traceback (most recent call last):
File "/usr/local/RNAErnie/sec.py", line 135, in
ssp_trainer = SspTrainer(args=args,
File "/usr/local/RNAErnie/secondary_structure.py", line 1158, in *init*
super(SspTrainer, self).*init*(
File "/usr/local/RNAErnie/base_classes.py", line 167, in *init*
self.name_pbar = self.compute_metrics.metrics[0]
AttributeError: 'NoneType' object has no attribute 'metrics'

**Comment by CatIIIIIIII** [comment]
replace 
`self.name_pbar = self.compute_metrics.metrics[0]`
in base_classes.py with
```
if self.compute_metrics:
    self.name_pbar = self.compute_metrics.metrics[0]
else:
    self.name_pbar = "loss"
```

**Comment by cyxiang1027** [comment]
Thank you very much for your reply. It's working now.
