### ISSUE TITLE
关于import paddle失败的

### ISSUE THREAD

**Issue by zhendejuzi** [CatIIIIIIII/RNAErnie#3]
你好，我利用conda env create -f environment.yml进行安装。
但是在测试的时候，报错：

Python 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import paddle
Error: Can not import avx core while this file exists: /data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /data/wsj/software/anaconda3/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

我的服务器版本：
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

该怎么解决？

**Comment by CatIIIIIIII** [comment]
你好！

这看起来是gcc的版本问题，可以尝试安装paddlepaddle==2.4

https://github.com/PaddlePaddle/Paddle/issues/44571

**Comment by CatIIIIIIII** [comment]
Considering most of the researchers will prefer to use transformers and pytorch as backend. So, I transfer my work to transformers and train a pytorch model from scratch. The new model is trained with more powerful settings: The max model length is up to 2048 now and the pretraining dataset is the newest version of rnacentral, which contains about 31 million RNA sequences after length filtering (<2048). This pytorch version model has been uploaded to huggingface at https://huggingface.co/WANGNingroci/RNAErnie and the training framework/tokenization is located at https://github.com/CatIIIIIIII/RNAErnie2. (NOTE: the tokenization is a little different from the original paddle implementation). Moreover, [Multimolecule](https://github.com/DLS5-Omics/multimolecule) are implementing current most powerful RNA language model with transformers and pytorch. Our model also could be accessed at https://huggingface.co/multimolecule/rnaernie.
