### ISSUE TITLE
libcudnn.so issues paddle

### ISSUE THREAD

**Issue by jiosephlee** [CatIIIIIIII/RNAErnie#8]
Operating System: Ubuntu 18.04
CUDA Version: 11.6

I am experiencing an issue where PaddlePaddle cannot load the libcudnn.so library, despite cuDNN being installed in my conda environment. Here is the error message I received:
```
W1022 17:03:18.422421 3492679 dynamic_loader.cc:305] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with PaddlePaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
```
Here is the full traceback:
```
Traceback (most recent call last):
  File "run_ssp.py", line 159, in <module>
    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 340, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 841, in __init__
    self.embeddings = ErnieEmbeddings(vocab_size, hidden_size,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 59, in __init__
    self.word_embeddings = nn.Embedding(vocab_size,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1453, in __init__
    self.weight = self.create_parameter(
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 472, in __call__
    out_var = _C_ops.truncated_gaussian_random(
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:59)
  [operator < truncated_gaussian_random > error]
```

**Comment by jiosephlee** [comment]
The installation process seems to install cuDNN into the conda environment as `/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/nvidia/cudnn/lib/libcudnn.so.8`. Since, paddle seems to look for `libcudnn.so`, I was able to address this issue by creating a symbolic link in my conda environment to make libcudnn.so point to libcudnn.so.8 with 

```
ln -s /opt/conda/envs/RNAErnie/lib/python3.8/site-packages/nvidia/cudnn/lib/libcudnn.so.8 /opt/conda/envs/RNAErnie/lib/python3.8/site-packages/nvidia/cudnn/lib/libcudnn.so
``` 

and then exporting the path accordingly.

However, I'm now facing the issue:

```
Traceback (most recent call last):
  File "run_ssp.py", line 159, in <module>
    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 340, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 841, in __init__
    self.embeddings = ErnieEmbeddings(vocab_size, hidden_size,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 59, in __init__
    self.word_embeddings = nn.Embedding(vocab_size,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1453, in __init__
    self.weight = self.create_parameter(
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/opt/conda/envs/RNAErnie/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 472, in __call__
    out_var = _C_ops.truncated_gaussian_random(
SystemError: (Fatal) Operator truncated_gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
```

**Comment by CatIIIIIIII** [comment]
It seems this caused by the version of cuda. You could try cuda=10.2, paddle2.3 works fine on it. Moreover, you could try install by the official site at [https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/macos-pip.html#old-version-anchor-19-V2.3](https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/macos-pip.html#old-version-anchor-19-V2.3) . Some said that they solve the similar problem by install using pip.

**Comment by jiosephlee** [comment]
Thanks for the help! As you said, this was addressed by directly installing `paddlepaddle-gpu` for the right cuda using the directions from the official site (via pip)
